# Generated by Django 4.1.6 on 2023-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.JSONField(default={'audio': 5, 'image': 4, 'text1': 1, 'text2': 2, 'text3': 3, 'video': 6}),
        ),
    ]
